server:
  port: 7070
  
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 200
      initialSize: 2
      maxWait: 5000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxOpenPreparedStatements: 20
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      web-stat-filter:
        exclusions:  "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/act_demo?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456    

  activiti: 
    check-process-definitions: true  # activti是否自动部署
    db-identity-used: true  #是否使用activti自带的用户体系
    database-schema-update: true  #是否每次都更新数据库
    #check-process-definitions: false  # activti是否自动部署
    #db-identity-used: false  #是否使用activti自带的用户体系

    
mybatis-plus:
  #Mapper 所对应的 XML 文件位置
  mapper-locations: classpath*:/mapper/*/*Mapper.xml,classpath*:/mapper/*Mapper.xml
  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.act.demo.model.*
  configuration:
    #只对非嵌套的 resultMap 进行自动映射
    auto-mapping-behavior: partial
    #当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: failing
  #全局配置
  global-config:
    #开启自动刷新 Mapper 对应的 XML 文件；生产环境关闭
    db-config:
      #数据库类型
      db-type: mysql
      #全局默认主键类型
      id-type: ID_WORKER
      #表名前缀
      table-prefix: t_
      #逻辑已删除值
      logic-delete-value: 1
      #逻辑未删除值
      logic-not-delete-value: 0
  